name: 'Checks'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  check:
    name: Run checks.
    runs-on: ubuntu-latest
    env:
      GC_DONT_GC: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0

      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/lb41az54kzk6j12p81br4bczary7m145/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            experimental-features = nix-command flakes ca-references

      - name: Check that node-env is up-to-date
        run: |
          nix run '.#update-package-lock'
          nix run '.#refresh-node-env'
          [[ -z $(git status -s) ]] || ( \
            echo "Changed package.json or package-lock.json.";
            echo "Please run 'nix run .#update-package-lock' and 'nix run .#refresh-node-env'."; \
            exit 1 \
          )

      - name: Run checks
        run: |
          nix flake check -L .
